### ISSUE TITLE
BearsUpThere QB tweak

### ISSUE THREAD

**Issue by thebrodieman** [BosslandGmbH/Honorbuddy-Quest-Behaviors#1]
BearsUpThere for Mount Hyjal quests "Bears Up There" and "Those Bears Up There" was missing a component to make it truly cross compatible between the two quests.

The aura given to players when "riding" the tree differs between the yellow quest version and the Molten Front daily.
I added a second variable for this aura ID, and updated the bool function that checks if we have it to return true if we have at least 1 of those auras.

Please find updated file below!

[BearsUpThere.zip](https://github.com/BosslandGmbH/Honorbuddy-Quest-Behaviors/files/367920/BearsUpThere.zip)

**Comment by aevitas** [comment]
Please submit any improvements and/or changes as a pull request. If you're unsure how to do this, see [fork a repo](https://help.github.com/articles/fork-a-repo/) for more details. 

I'll keep the issue open so you can reference it in your pull request.

**Comment by thebrodieman** [comment]
Pull request made. Closing.
