### ISSUE TITLE
ForcedMount using "First" flying mount

### ISSUE THREAD

**Issue by thebrodieman** [BosslandGmbH/Honorbuddy-Quest-Behaviors#17]
ForcedMount is using the First() mount on the list as our mount, instead of user defined.

**Comment by thebrodieman** [comment]
Am trying to submit my change, created a branch just for it, but its saying that I don't have permission to do so. Any help in the matter would be great, changes are ready for push once cleared up.

**Comment by jakobbotsch** [comment]
From the command line you can do:

```
git checkout master
git fetch upstream
git reset --hard upstream/master
git push -f
git checkout -b forcedmount-fix
```

then make your changes and commit/push that. Note that this will throw away your previous changes. If you are using a GUI it's probably easier for you to delete your fork and recreate it.

**Comment by thebrodieman** [comment]
Submitted...but I've kind of made a total mess of this. Every time I try to start over, it seems to get more complicated. Not very user friendly for novice users of this interface...will probably be the last time I submit something through this because I'm still not sure it even sent what I wanted, keeps sending the stuff I sent last month...

**Comment by thebrodieman** [comment]
Can't fix the fork. Can't delete the fork. Going to leave it be and use assembla from now on.
