### ISSUE TITLE
MrFishIt - Pool fishing does not work

### ISSUE THREAD

**Issue by hbcode2** [BosslandGmbH/Honorbuddy-Quest-Behaviors#28]
It does not appear that pool fishing is working at all with MrFishIt.  Using questing profile, if you direct him to a certain location and using x, y, z point him where to fish, it appears to be working.  If you remove x, y, z and add a pool ID and MoveToPool = true, it spews a bunch of errors.

After messing with it for a bit, it doesn't appear the **hasPoolFound** property is being called which populates **_PoolGUID** which then in turn allows the pool fishing.  I tried to mess with it for a few hours to see if I could determine why it wasn't being called, but I could not.

To reproduce, I am in Suramar and standing near (about 10 yards away) from a Runescale Koi School (ID: 246492).  I use this in my quest profile to fish the school (and move to it):

`<MoveTo Nav="Fly" X="2351.11" Y="5250.911" Z="98.34917" />`
`<RunTo X="2351.11" Y="5250.911" Z="98.34917" />`
`<CustomBehavior File="MrFishIt" PoolId="246492" CollectItemId="133719" MoveToPool="true" CollectItemCount="1" MaxCastRange="20" MinCastRange="15"/>`

Anything else you need, just let me know.

**Comment by jakobbotsch** [comment]
Thanks for the report!

**Comment by hbcode2** [comment]
Thanks for the fix!  I will test it soon! :)

**Comment by hbcode2** [comment]
If I want a request for something, do I put in an issue item?  

I was looking for something that would fish up X times before it quit.  Something like a MaxSuccessfulCasts and when it hits the number it stops.  I have a While statement and I'm looking for 2-3 items in 1 spot and I can only specify 1 ID.  I wanted it to keep looping, but right now it gets stuck on the 1 item.  Also if I run out of Arcane Lure, it'll never find the 1 item and there's no way to detect if I have any more Arcane Lure either.

Thanks!

**Comment by hbcode2** [comment]
While it appears to be doing better, I am not seeing it go to pools.   I get this nonstop: [MrFishIt-767ce8(warning)] Timer for moving to ground elapsed, blacklisting for 2 minutes.

Here's screenshot of the current list of pools as I was starting it.
![image](https://cloud.githubusercontent.com/assets/21277329/20153262/eb361a3c-a68f-11e6-9613-73ce3fa3c07f.png)

Here's the profile I created just for this test.
[TestPoolProfiles.zip](https://github.com/BosslandGmbH/Honorbuddy-Quest-Behaviors/files/581784/TestPoolProfiles.zip)

No matter where I start it, on profile 1, it runs to X="2386.738" Y="5236.311" Z="97.10383" and just sits on a rock at the same place until it blacklists above and then stops because it has nothing more to do.  On profile 2, it just sits in the RunTo location and waits until it blacklists.

Here is my log file:
[11520 2016-11-09 15.34.txt](https://github.com/BosslandGmbH/Honorbuddy-Quest-Behaviors/files/581788/11520.2016-11-09.15.34.txt)

Any suggestions?  Am I doing something wrong?

**Comment by ghost** [comment]
The pool might be too far from land and require water walking to fish. The QB doesn't support walkwalking and will only fish from pools that are within 15 to 20 yards from land.
